"""Phase 3/4: write the .memory/ layer — graph.json, per-file summaries, index.md."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import networkx as nx

from .graph_builder import graph_to_json

INDEX_TEMPLATE = """# Codebase Memory (.memory/)

Generated by CMS on {generated}.

This folder is a structural + semantic map of the codebase, built for AI agents
(and humans) to understand where things live before reading raw code.

## Contents

| File | What it is |
|---|---|
| `clean_tree.md` | Filtered directory tree with per-file line counts, sizes, languages |
| `clean_tree.json` | Machine-readable version with full metadata |
| `graph.json` | Knowledge graph: file/class/function nodes with summaries, connected by CONTAINS / IMPORTS / CALLS / INHERITS edges |
| `summaries/` | Per-file low-resolution summaries as readable markdown |
| `features/` | Feature traces: flow, inputs/outputs, verification checklist per feature |

## Stats

- Files scanned: {file_count}
- Graph nodes: {node_count} · edges: {edge_count}
- Summarized files: {summary_count}

## How to query

```bash
cms query "where is the ignore pattern filtering logic?"
```

```python
from cms import CodebaseMemory

mem = CodebaseMemory.load(".memory/graph.json")
for hit in mem.query_intent("clean directory tree building", top_k=5):
    print(hit.path, hit.lines, hit.summary)
```

## Commit or ignore?

Your call: commit `.memory/` so agents always have the map after cloning, or
add it to `.gitignore` and regenerate locally with `cms run-all`.
"""


def export_graph(graph: nx.DiGraph, memory_dir: Path) -> Path:
    memory_dir.mkdir(parents=True, exist_ok=True)
    out = memory_dir / "graph.json"
    # atomic replace: the UI server may be reading while the watcher writes;
    # unique temp name + retry so CONCURRENT writers can't truncate each
    # other's temp file mid-replace (Windows PermissionError race)
    from .semantic_state import atomic_write_json

    atomic_write_json(out, graph_to_json(graph))
    return out


def export_summaries(graph: nx.DiGraph, memory_dir: Path) -> int:
    """One markdown file per summarized source file, mirroring the source layout."""
    summaries_dir = memory_dir / "summaries"
    count = 0
    for node_id, attrs in graph.nodes(data=True):
        if attrs.get("type") != "file" or not attrs.get("summary"):
            continue
        rel = attrs["path"]
        target = summaries_dir / (rel + ".md")
        target.parent.mkdir(parents=True, exist_ok=True)
        provider = (attrs.get("summary_meta") or {}).get("provider", "?")
        target.write_text(
            f"# {rel}\n\n"
            f"*{attrs.get('line_count', '?')} lines · provider: {provider}*\n\n"
            f"{attrs['summary']}\n",
            encoding="utf-8",
        )
        count += 1
    return count


def export_features(graph: nx.DiGraph, memory_dir: Path) -> int:
    """One markdown trace per feature under .memory/features/."""
    from .features import get_features

    features = get_features(graph)
    if not features:
        return 0
    features_dir = memory_dir / "features"
    features_dir.mkdir(parents=True, exist_ok=True)
    toc = ["# Feature Traces\n"]
    for f in features:
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in f["name"])
        member_lines = "\n".join(f"- `{m}`" for m in f.get("members", []))
        (features_dir / f"{safe}.md").write_text(
            f"# Feature: {f['name']}\n\n"
            f"*source: {f.get('source', '?')}"
            + (f" · connects: {', '.join(f['connects'])}" if f.get("connects") else "")
            + "*\n\n"
            + (f"> {f['description']}\n\n" if f.get("description") else "")
            + f"{f.get('summary', '')}\n\n"
            f"## Members\n{member_lines}\n",
            encoding="utf-8",
        )
        toc.append(f"- [{f['name']}]({safe}.md) — {f.get('description') or f.get('source', '')}")
    (features_dir / "README.md").write_text("\n".join(toc) + "\n", encoding="utf-8")
    return len(features)


def export_index(graph: nx.DiGraph, memory_dir: Path, file_count: int) -> None:
    summary_count = sum(
        1 for _, a in graph.nodes(data=True) if a.get("type") == "file" and a.get("summary")
    )
    (memory_dir / "index.md").write_text(
        INDEX_TEMPLATE.format(
            generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            file_count=file_count,
            node_count=graph.number_of_nodes(),
            edge_count=graph.number_of_edges(),
            summary_count=summary_count,
        ),
        encoding="utf-8",
    )
